CREATE TABLE tb_func (
    matricula INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    datanascimento DATE NOT NULL,
    salario NUMERIC(10,2) NULL,
    dataadmissao DATE DEFAULT CURRENT_DATE,
    datademissao DATE NULL,
    inicioferias DATE NULL,
    fimferias DATE NULL,
    status_func VARCHAR(20) CHECK (status_func IN ('ATIVO','INATIVO','FERIAS','LICENÇA','INSS')),
    coddepto INT
);


INSERT INTO tb_func (NOME, DATANASCIMENTO,SALARIO,DATAADMISSAO,DATADEMISSAO,INICIOFERIAS,FIMFERIAS, STATUS_FUNC, CODDEPTO)
VALUES ('ANA MARIA', '2000-01-01', 1200.55, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 1),
('JOSE HENRIQUE', '1998-11-20', 2575.55, '2005-09-01','2017-12-01',NULL,NULL, 'INATIVO', 7),
('ANA MARIA', '2002-08-21', 950.00, '2019-01-01',NULL,NULL,NULL, 'ATIVO', 6),
('LUAN FELIX', '1991-09-28', 3500.00, '2013-04-01',NULL,NULL,NULL, 'ATIVO', 1),
('FELIPE JOSE DOS SANTOS', '1996-01-11', 4000, '2011-05-01','2015-01-29',NULL,NULL, 'INATIVO', 2),
('MARCELO JOSE', '1980-10-05', 7000, '2000-05-01',NULL,'2019-05-01','2019-06-01', 'ATIVO', 2),
('MARIANA MARIA', '1987-02-08', 4500, '2010-01-01',NULL,NULL,NULL, 'INSS', 3),
('JULIANA MARIA DOS SANTOS', '2002-01-01', 2000, '2017-05-01',NULL,NULL,NULL, 'LICENÇA', 5),
('MARIA ALICIA', '2001-01-01', 950, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 4)

INSERT INTO tb_func (NOME, DATANASCIMENTO,SALARIO,STATUS_FUNC, CODDEPTO)
VALUES ('MARIA ALICIA', '2003-09-18', 950,  'ATIVO', 3)

SELECT *
FROM tb_func
ORDER BY NOME

SELECT *
FROM tb_func
ORDER BY NOME, SALARIO

SELECT *
FROM tb_func
ORDER BY NOME ASC, SALARIO DESC

SELECT  MATRICULA, NOME, DATADEMISSAO, STATUS_FUNC
FROM tb_func
WHERE DATADEMISSAO IS NULL
AND STATUS_FUNC = 'ATIVO'

SELECT  MATRICULA, NOME, DATADEMISSAO, STATUS_FUNC
FROM tb_func
WHERE DATADEMISSAO IS NULL
OR STATUS_FUNC = 'ATIVO'

SELECT 
MATRICULA, NOME, SALARIO, STATUS_FUNC
FROM tb_func
WHERE NOT STATUS_FUNC = 'ATIVO'

SELECT 
NOME,
SALARIO + 50 AS ADICAO,
SALARIO - 20 AS SUBTRACAO,
SALARIO * 1.20  AS AJUSTE_20_PCENTO,
SALARIO / 2 AS DIVISAO
FROM tb_func
WHERE STATUS_FUNC = 'ATIVO'


SELECT * 
FROM tb_func
WHERE STATUS_FUNC = 'ATIVO'

SELECT * 
FROM tb_func
WHERE DATANASCIMENTO >= '1999-01-01'

SELECT * 
FROM tb_func
WHERE SALARIO >= 2000 
AND SALARIO <= 4000

SELECT * 
FROM tb_func
WHERE STATUS_FUNC <> 'ATIVO'

SELECT * 
FROM tb_func
WHERE DATADEMISSAO IS NULL

SELECT * 
FROM tb_func
WHERE DATADEMISSAO  IS NOT NULL

SELECT * 
FROM tb_func
WHERE DATAADMISSAO BETWEEN '2012-01-01' AND '2018-12-20'

SELECT * 
FROM tb_func
WHERE CODDEPTO BETWEEN 5 AND 15

SELECT * 
FROM tb_func
WHERE STATUS_FUNC IN ('ATIVO','FERIAS')

SELECT * 
FROM tb_func
WHERE EXTRACT(MONTH FROM dataadmissao) IN (1, 2);


SELECT * 
FROM tb_func
WHERE EXTRACT(MONTH FROM dataadmissao) NOT IN (10, 11);

SELECT * 
FROM tb_func
WHERE NOME LIKE '%JOSE'

SELECT * 
FROM tb_func
WHERE NOME LIKE '%JOSE%'

SELECT * 
FROM tb_func
WHERE NOME LIKE 'JOSE%'

SELECT NOME, STATUS_FUNC,
CASE STATUS_FUNC
	WHEN 'ATIVO' THEN 'A'
	WHEN 'INATIVO' THEN 'I'
	WHEN 'FERIAS' THEN 'F'
ELSE
	'O'
END SIGLA_STATUS
FROM tb_func

SELECT NOME, SALARIO,
CASE 
	WHEN SALARIO > 1200 AND SALARIO < 1500 THEN SALARIO * 1.1
	WHEN SALARIO > 1501 AND SALARIO < 2000 THEN SALARIO * 1.2
	WHEN SALARIO < 1000 THEN SALARIO
END SALARIO_COM_REAJUSTE
 
FROM tb_func

SELECT DISTINCT NOME 
FROM tb_func

SELECT DISTINCT NOME, SALARIO
FROM tb_func

SELECT DISTINCT NOME, SALARIO, DATANASCIMENTO 
FROM tb_func

SELECT 
MATRICULA, 
NOME 
FROM tb_func
LIMIT 5


SELECT 
MATRICULA, 
NOME 
FROM tb_func
ORDER BY MATRICULA DESC
LIMIT 5